/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Pavilion_Brokendown(props) {
  const { nodes, materials } = useGLTF('/pavilion_v2_broken_down.glb')
  const roofTexture = useTexture('/textures/pavilion/roof.jpg')
  const stoneTexture = useTexture('/textures/pavilion/stone.jpg')
  const woodTexture = useTexture('/textures/pavilion/wood.jpg')

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} side={THREE.BackSide} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pillar.geometry}
        material={materials.Material}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={woodTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_bottom.geometry}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={roofTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window.geometry}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={woodTexture} vertexColors={false} transparent opacity="0.95" />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PillarFeet.geometry}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={stoneTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof.geometry}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={roofTexture} />
        <mesh castShadow receiveShadow geometry={nodes.Plane014.geometry}>
          <meshStandardMaterial map={roofTexture} />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_top.geometry}
        position={[0, 1, 0]}
        scale={[62.5, 1, 62.5]}
      >
        <meshStandardMaterial map={roofTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/pavilion_v2_broken_down.glb')
