/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import * as THREE from 'three'

export default function Pavilion(props) {
  const { nodes, materials } = useGLTF('/pavilion.glb')
  const roofTexture = useTexture('/textures/pavilion/roof.jpg')
  const roofTileTexture = useTexture('/textures/pavilion/roofTile.jpg')
  roofTileTexture.wrapS = THREE.RepeatWrapping
  roofTileTexture.wrapT = THREE.RepeatWrapping
  const roofEdgeTexture = useTexture('/textures/pavilion/roof_edge.jpg')

  const stoneTexture = useTexture('/textures/pavilion/stone.jpg')
  return (
    <RigidBody type="fixed" colliders={false}>
      <group {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_1.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_2.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_3.geometry}
            material={materials.wire_006134113}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_4.geometry}
            material={materials.wire_088199225}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_5.geometry}
            material={materials.wire_141007058}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_6.geometry}
            material={materials.wire_028089177}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_7.geometry}
            material={materials.wire_153228153}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_8.geometry}
            material={materials.wire_006134058}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_9.geometry}
            material={materials.wire_154215229}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_10.geometry}
            material={materials.wire_026177088}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_11.geometry}
            material={materials.wire_184155229}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_12.geometry}
            material={materials.wire_140088225}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_13.geometry}
            material={materials.wire_153228184}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_14.geometry}
            material={materials.wire_028149177}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_15.geometry}
            material={materials.wire_134110008}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Obj3d66_1606865_760_938_16.geometry}
            material={materials.wire_143224087}
          />
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_17.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_18.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_19.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_20.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_21.geometry}>
            <meshStandardMaterial map={roofEdgeTexture} vertexColors={false} />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Obj3d66_1606865_760_938_22.geometry}>
            <meshStandardMaterial map={roofTexture} vertexColors={false} />
          </mesh>
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/pavilion.glb')
