/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/table.glb')
  const tableTexture = useTexture('/textures/table/granite.png')
  tableTexture.wrapS = tableTexture.wrapT = THREE.RepeatWrapping
  tableTexture.repeat.set(20, 20)

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chess_1.geometry}
          material={null}
          scale={0.01}
        >
          <meshStandardMaterial map={tableTexture} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/table.glb')
