/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useTexture, Float } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import * as THREE from 'three'

export default function WaterLantern(props) {
  const lightRef = useRef()
  const candleRef = useRef()
  const bodyRef = useRef()

  const { nodes, materials } = useGLTF('/water_lantern.glb')

  const min = 0.05
  const max = 1.5
  const flickerOffset = Math.random() * 0.2
  const speed = 0.75 + flickerOffset * 1.1
  useFrame((state) => {
    const t = state.clock.elapsedTime
    const intensity = min + (max - min) * (0.5 + 0.5 * Math.sin(t * speed) + flickerOffset)
    lightRef.current.intensity = intensity
    // const flameOpacity = THREE.MathUtils.clamp(
    //   THREE.MathUtils.mapLinear(intensity, min, max, 0.02, 0.12),
    //   0.08,
    //   0.3
    // )
    // candleRef.current.opacity = flameOpacity
  })

  const paperTexture = useTexture('/textures/water_lantern/paper.jpg')
  const userTexture = useTexture(props.image ?? '/textures/water_lantern/paper.jpg')
  const candleTexture = useTexture('/textures/transparent_radial.png')

  return (
    <RigidBody
      ref={bodyRef}
      userData={{ lantern: true }}
      type="dynamic"
      linearDamping={2}
      angularDamping={1}
      lockRotations
      lockTranslations={[false, true, true]}
      position={props.position}
    >
      <CuboidCollider args={[0.5, 0.5, 0.5]} position={[0, 0.05, 0]} />{' '}
      <Float speed={6} floatIntensity={0.08} rotationIntensity={0.01}>
        <group {...props} dispose={null} rotation={[0, Math.PI / 15, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.base.geometry}
            material={materials.wood_textureA}
            scale={0.004}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lantern.geometry}
            material={materials.patternBB}
            scale={0.004}
            emissive={'#ffffff'}
            emissiveIntensity={0.3}
          >
            <meshStandardMaterial
              map={paperTexture}
              transparent
              opacity={0.8}
              side={THREE.DoubleSide}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.legs.geometry}
            material={materials.wood_textureA}
            scale={0.004}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            material={materials.patternBB}
            position={[0, 0.105, 0.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.123, 1, 0.123]}
            emissive={'#ffffff'}
            emissiveIntensity={0.1}
          >
            <meshStandardMaterial
              map={userTexture}
              transparent
              opacity={0.8}
              side={THREE.BackSide}
              alphaTest={0.01}
            />
          </mesh>
          <pointLight
            ref={lightRef}
            position={[0, 0, 0]}
            intensity={2}
            decay={2}
            rotation={[-Math.PI / 2, 0, 0]}
            distance={0.75}
            color={'#ffddaa'}
          />
          <sprite scale={[0.4, 0.4, 1]} position={[0, 0.2, 0]} renderOrder={10}>
            <spriteMaterial
              ref={candleRef}
              map={candleTexture}
              color={'#ffddaa'}
              transparent={true}
              opacity={0.16}
              depthWrite={false}
              depthTest={false}
              blending={THREE.AdditiveBlending}
              toneMapped={false}
            />
          </sprite>
        </group>
      </Float>
    </RigidBody>
  )
}
