/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function WaterLanternEditable(props) {
  const lightRef = useRef()
  const { nodes, materials } = useGLTF('/water_lantern_editable.glb')

  useFrame((state) => {
    const t = state.clock.elapsedTime
    const min = 0.1
    const max = 2.5
    const speed = 0.75
    lightRef.current.intensity = min + (max - min) * (0.5 + 0.5 * Math.sin(t * speed))
  })

  // const paperTexture = useTexture(props.image)
  const paperTexture = useTexture('/textures/water_lantern/paper.jpg')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials.wood_textureA}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lantern.geometry}
        material={materials.patternBB}
        scale={0.004}
      >
        <meshStandardMaterial map={paperTexture} transparent opacity={0.99} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.legs.geometry}
        material={materials.wood_textureA}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.patternBB}
        position={[0.094, 0.075, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.095, 1, 0.094]}
      >
        <meshStandardMaterial map={paperTexture} transparent opacity={0} />
      </mesh>
      <pointLight
        ref={lightRef}
        position={[0, 0, 0]}
        intensity={543.514}
        decay={2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/water_lantern_editable.glb')
